name: patino1
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bottom_navy_bar: ^6.0.0
  brasil_fields: ^1.1.2
  cupertino_icons: ^1.0.2
  rxdart: ^0.22.6
  shared_preferences: ^2.0.5
  validadores: ^1.0.2
  flutter_mobx: 
  mobx:
  flutter_modular:
  flutter_icons: ^1.1.0
  auto_size_text:  


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  mobx_codegen:  
  flutter_launcher_icons: "^0.8.0"


flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/logo_dev.jpg"

flutter:
  uses-material-design: true
  assets:
      - assets/logo.png  

scripts:
  dev: flutter pub get & flutter pub run build_runner watch --delete-conflicting-outputs 
  build: flutter pub run build_runner build --delete-conflicting-outputs 
  clean_project: flutter clean & flutter pub get & flutter pub run build_runner watch --delete-conflicting-outputs 
  web: flutter run -d chrome
  mobile: flutter run 
  build_icone: flutter pub run flutter_launcher_icons:main